### ISSUE TITLE
Failing for test case: Jest : Unable to find native implementation, or alternative implementation for WebSocket!

### ISSUE THREAD

**Issue by pratikt-cuelogic** [sonaye/mobx-apollo#17]
```
 FAIL  src/stores/userStore.test.js
  ● Test suite failed to run

    Unable to find native implementation, or alternative implementation for WebSocket!
      
      at new SubscriptionClient (node_modules/subscriptions-transport-ws/dist/client.js:28:19)
      at new WebSocketLink (node_modules/apollo-link-ws/lib/bundle.umd.js:25:40)
      at Object.<anonymous> (src/api/GqlClient.js:20:3)
      at Object.<anonymous> (src/stores/userStore.js:4:18)
      at Object.<anonymous> (src/stores/userStore.test.js:1:120)
```

Whereas my GqlClient.js is 

```
import fetch from 'isomorphic-fetch';
import { ApolloClient, HttpLink, InMemoryCache } from 'apollo-client-preset';
import { getMainDefinition } from 'apollo-utilities';
import { split } from 'apollo-link';
import { WebSocketLink } from 'apollo-link-ws';

global.fetch = fetch;

const uri = 'https://api.graph.cool/simple/v1/cjei7bof31u8101243cyfqgjw';
const wsUri = 'wss://subscriptions.us-west-2.graph.cool/v1/cjei7bof31u8101243cyfqgjw';

export const GqlClient = new ApolloClient({
  // link: new HttpLink({ uri }),
  link: split(
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query);
      return kind === 'OperationDefinition' && operation === 'subscription';
    },
    new WebSocketLink({ uri: wsUri, options: { reconnect: true } }),
    new HttpLink({ uri })
  ),
  cache: new InMemoryCache()
});
```

Any suggestion to proceed with test cases would be really helpful .. thanks in advance

**Comment by sonaye** [comment]
Hey, I will be updating the example for subscriptions in the next couple of hours, so keep any on that. Also, try installing subscriptions-transport-ws as it should fix the issue.

**Comment by sonaye** [comment]
Updated. Let me know if your issue is fixed.
